# AceAgent 配置文件示例
# 复制此文件到 ~/.aceagent/config.yaml 并根据需要修改配置

# LLM提供商配置
default_provider: openai

# OpenAI配置
openai_api_key: your_openai_api_key_here
openai_default_model: gpt-4
openai_base_url: https://api.openai.com/v1  # 可选，自定义API端点

# Anthropic配置
anthropic_api_key: your_anthropic_api_key_here
anthropic_default_model: claude-3-sonnet-20240229

# 豆包配置
doubao_api_key: your_doubao_api_key_here
doubao_default_model: doubao-pro-4k
doubao_base_url: https://ark.cn-beijing.volces.com/api/v3  # 可选

# 生成参数
temperature: 0.7
max_tokens: 2000
top_p: 1.0

# 工具配置
file_edit_backup: true  # 是否在编辑文件前创建备份
command_timeout: 30     # 命令执行超时时间（秒）

# 轨迹记录配置
trajectory_enabled: true
trajectory_db_path: ~/.aceagent/trajectories.db

# 日志配置
log_level: Information  # Trace, Debug, Information, Warning, Error, Critical
log_file: ~/.aceagent/logs/aceagent.log

# Lakeview服务配置（可选）
lakeview_enabled: false
lakeview_api_key: your_lakeview_api_key_here
lakeview_base_url: https://api.lakeview.com

# 代理配置（可选）
# http_proxy: http://proxy.example.com:8080
# https_proxy: https://proxy.example.com:8080
# no_proxy: localhost,127.0.0.1

# 高级配置
max_conversation_history: 50  # 最大对话历史记录数
auto_save_trajectory: true     # 是否自动保存轨迹
parallel_tool_execution: false # 是否并行执行工具（实验性功能）